/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package foundationdb_fslayer;

import com.apple.foundationdb.FDB;
import foundationdb_fslayer.fdb.FoundationFileOperations;
import foundationdb_fslayer.fdb.FoundationLayer;
import foundationdb_fslayer.fuse.FuseLayer;

import java.nio.file.Paths;

public class App {


  public static void main(String[] args) {
    FoundationFileOperations dbOps = new FoundationLayer(630);
    FuseLayer fuseLayer = new FuseLayer(dbOps);

    try {
      fuseLayer.mount(Paths.get(args[0]), true, true);
    } finally {
      fuseLayer.umount();
    }

  }

}




